--------------------------------------------------------
--  파일이 생성됨 - 수요일-9월-07-2022   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table MEMBER
--------------------------------------------------------

  CREATE TABLE "HR"."MEMBER" 
   (	"EMAIL" VARCHAR2(100 BYTE), 
	"PW" VARCHAR2(100 BYTE), 
	"TEL" VARCHAR2(100 BYTE), 
	"ADDRESS" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into HR.MEMBER
SET DEFINE OFF;
Insert into HR.MEMBER (EMAIL,PW,TEL,ADDRESS) values ('sd','sdfsd','266262ff','6262s6sff');
Insert into HR.MEMBER (EMAIL,PW,TEL,ADDRESS) values ('16161626','565942959','494815195','841891511');
Insert into HR.MEMBER (EMAIL,PW,TEL,ADDRESS) values ('admin','asdf','65656565','484624949');
--------------------------------------------------------
--  DDL for Index M_EMAIL_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HR"."M_EMAIL_PK" ON "HR"."MEMBER" ("EMAIL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table MEMBER
--------------------------------------------------------

  ALTER TABLE "HR"."MEMBER" ADD CONSTRAINT "M_EMAIL_PK" PRIMARY KEY ("EMAIL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HR"."MEMBER" MODIFY ("ADDRESS" NOT NULL ENABLE);
  ALTER TABLE "HR"."MEMBER" MODIFY ("TEL" NOT NULL ENABLE);
  ALTER TABLE "HR"."MEMBER" MODIFY ("PW" NOT NULL ENABLE);
  ALTER TABLE "HR"."MEMBER" MODIFY ("EMAIL" NOT NULL ENABLE);
